### ISSUE TITLE
An error running at openwrt with lua5.1.5

### ISSUE THREAD

**Issue by leetking** [kikito/md5.lua#15] opened 2017-05-20 11:46 UTC
openwrt version: ` CHAOS CALMER (15.05.1, r48532)`
my router CPU: `ar71xx`
lua version: `Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio (double int32)`
when I run, some thing happened, as shown blow.
```lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio (double int32)
> md5 = require("md5")
> print(md5.sumhexa(""))
./md5.lua:385: bad argument #2 to 'format' (integer expected, got number)
stack traceback:
	[C]: in function 'format'
	./md5.lua:385: in function <./md5.lua:384>
	(tail call): ?
	stdin:1: in main chunk
	[C]: ?
> 
```
OK, I can bear, then I improve the function `md5.tohex()`.
```lua
function md5.tohex(s)                                                               
  -- return format("%08x%08x%08x%08x", str2bei(sub(s, 1, 4)), str2bei(sub(s, 5, 8)), str2bei(sub(s, 9, 12)), str2bei(sub(s, 13, 16)))                                                
  local ret = ""                                                           
  local step = 2                                                 
  for i = 1, 16-step+1, step do                                        
      ret = ret..format("%04x", str2bei(sub(s, i, i+step-1)))          
  end                                                                 
  return ret                                                                                      
end
```
I kown it is so slow in lua, but it can work corretly.
When I run it at my pc, no issue.

**Comment by Positive07** [comment] 2017-05-21 03:15
First I want to point out that this is super odd behaviour and really unexpected, it's not a bug of md5.lua but a bug on OpenWRT Lua version (probably a design choice for performance, but it's a breaking change).

If the problem is that `number` and `integer` are represented with a different internal type, then maybe this change to `str2bei` would also fix the issue:
```lua
local toint = math.tointeger or math.floor

local function str2bei(s)
  local v=0
  for i=1, #s do
    v = v * 256 + byte(s, i)
  end
  return toint(v)
end
```
Try it and let me know what you get.

If this doesn't fix the issue, then the error is that it can't represent 32 bit integers... which would imply that a more complex solution like the one you posted above is needed.

However implementing such a thing would slow this library down and would only benefit the odd OpenWRT Lua implementation. So maybe fork it? Or make an OpenWRT branch?

**Comment by leetking** [comment] 2017-05-21 04:01
tks a lot. for the 'odd' OpenWRT, I try to use my complex solution -_-||... I am not care about it too. Now I am in class, at the next time, I report my test of your suggest.

**Comment by leetking** [comment] 2017-05-21 13:29
I try your suggest, the same problem happened. :sob:
but I still thanks you.

**Comment by Positive07** [comment] 2017-05-21 14:42
All right, try to test if this line fails:
```lua
string.format("%08x", 1)
```

If it does, then we could do this in `md5.lua`:
```lua
local UINT32 = pcall(string.format, "%08x", 1)

if UINT32 then
  return format("%08x%08x%08x%08x", str2bei(sub(s, 1, 4)), str2bei(sub(s, 5, 8)), str2bei(sub(s, 9, 12)), str2bei(sub(s, 13, 16)))
else
  return format("%06x%06x%06x%06x%06x%02x", str2bei(sub(s, 1, 3)), str2bei(sub(s, 4, 6)), str2bei(sub(s, 7, 9)), str2bei(sub(s, 10, 12)),str2bei(sub(s, 13, 15)), str2bei(sub(s, 16, 16)))
end
```

(Formatting could be improved but that is the idea...

**Comment by leetking** [comment] 2017-05-22 04:24
When I test
```lua
pcall(string.format, "%08x", 1)
```
It work successfully.

I chage it to
```lua
pcall(string.format, "%08x", (256^3)*255) -- It will reach the max singned int.
```
it throw the same error upon.

so, I improve to this.
```lua
local UINT32 = pcall(string.format, "%08x", 256^3*255)
if UINT32 then                                                                     
  return format("%08x%08x%08x%08x", str2bei(sub(s, 1, 4)), str2bei(sub(s, 5, 8)), str2bei(sub(s, 9, 12)), str2bei(sub(s, 13, 16)))
else                                                                     
   return format("%06x%06x%06x%06x%06x%02x", str2bei(sub(s, 1, 3)), str2bei(sub(s, 4, 6)), str2bei(sub(s, 7, 9)), str2bei(sub(s, 10, 12)),str2bei(sub(s, 13, 15)), str2be
end 
```
It work right! tks a lot. :gift:

**Comment by Positive07** [comment] 2017-05-22 04:37
We could include this solution in `md5.lua` if @kikito approves it!

Note that `2^33` should also overflow the int32 size, `256^3*255` can only be represented with mantissa so it's not a safe way to check for ints.

So if you can test with `2^33` too I would appreciate it (that would probably be the last thing I ask, then I'll submit a PR with the proposed fix so kikito can check if it could be merged)

```lua
local UINT32 = pcall(string.format, "%08x", 2^33)
if UINT32 then                                                                     
  return format("%08x%08x%08x%08x", str2bei(sub(s, 1, 4)), str2bei(sub(s, 5, 8)), str2bei(sub(s, 9, 12)), str2bei(sub(s, 13, 16)))
else                                                                     
   return format("%06x%06x%06x%06x%06x%02x", str2bei(sub(s, 1, 3)), str2bei(sub(s, 4, 6)), str2bei(sub(s, 7, 9)), str2bei(sub(s, 10, 12)),str2bei(sub(s, 13, 15)), str2be
end 
```

**Comment by leetking** [comment] 2017-05-22 07:00
I think we should test `2^32`, the reason you pointing out is that my router only support `signed integer 32 bits` and not support `unsigned int 32`, so It supports the maxisal `signed integer` that is `2^31-1` and for the maxisal `unsigned integer` `2^32-1` doesn't. for this case, `lua` convert it to type of `number`, so when we use function `format` to do it, get a error.
so I suggest we should use `2^31-1` to test it and avoid some platform that support `unsigned integer 32 bits` to use the 'long format string'.
and why does the `256^3*255` can work? It just covers the signed bit :laughing: 
ps: my english is pool, thanks you to bear. :rofl:

**Comment by kikito** [comment] 2017-05-22 10:26
Hi, thanks a lot @Positive07 for investigating this issue.

> We could include this solution in md5.lua if @kikito approves it!

Can someone send me a PR (ideally, with a test spec showing the new functionality)? I think I understand the problem but I'm not 100% sure about how to include all this.

**Comment by Positive07** [comment] 2017-05-22 13:25
Including this is not hard, basically the definition of `UINT32` would happen once, at the top of everything. Then the if conditional would go in `md5.tohex` and that is it.

Most normally Lua uses a `double` type that handles both `floats` and `signed integers` with more than 32 bits of precision, so testing would normally default to `UINT32` being `true`.

You would need some kind of global that makes the `UINT32` variable `false` externally, or make a fake `string.format` that fails when passed a number that isn't in the range of an `int32`, to test the second branch with the `%06x%06x%06x%06x%06x%02x` format string... So testing this would be kinda tricky.

I'll submit a PR without the test and once we decide how to handle the testing part I'll make a second commit with the appropriate tests

**Closed** 2017-06-29 02:00 UTC
